package com.mms.dao.generate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY".
 */
public class City {

    private Long id;
    private int cityId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String pinyin;
    private long lastUseTime;

    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    public City(Long id, int cityId, String name, String pinyin, long lastUseTime) {
        this.id = id;
        this.cityId = cityId;
        this.name = name;
        this.pinyin = pinyin;
        this.lastUseTime = lastUseTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCityId() {
        return cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPinyin() {
        return pinyin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public long getLastUseTime() {
        return lastUseTime;
    }

    public void setLastUseTime(long lastUseTime) {
        this.lastUseTime = lastUseTime;
    }

}
